version: "3.8"

services:
  minio:
    image: minio/minio:latest
    container_name: minio-container
    ports:
      - "9003:9003" # Console do MinIO
      - "9000:9000" # API S3
    environment:
      MINIO_ROOT_USER: miniouser
      MINIO_ROOT_PASSWORD: miniosecret
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9003"
    restart: always

volumes:
  minio-data:
